# Runestones
runes = "Runestone"
yr_1 = "Yellow Runestone 1"
yr_2 = "Yellow Runestone 2"
yr_3 = "Yellow Runestone 3"
rd_1 = "Red Runestone 1"
rd_2 = "Red Runestone 2"
rd_3 = "Red Runestone 3"
bl_1 = "Blue Runestone 1"
bl_2 = "Blue Runestone 2"
bl_3 = "Blue Runestone 3"
gn_1 = "Green Runestone 1"
gn_2 = "Green Runestone 2"
gn_3 = "Green Runestone 3"
bf_13 = "Final Runestone "
# Shards
shard = "Shards"
shard_fp = "Lich Shard"
shard_mk = "Dragon Shard"
shard_cs = "Chimera Shard"
shard_sd = "Plague Fiend Shard"
shard_fr = "Spider Queen Shard"
shard_dl = "Genie Shard"
shard_id = "Yeti Shard"
shard_dw = "Shadow Wraith Shard"
# Legendary Weapons
lw = "Legendary Weapons"
lw_fp =  "The Good Book"
lw_mk =  "Ice Axe"
lw_cs =  "Scimitar of Decapitation"
lw_sd =  "Javelin of Blinding"
lw_fr =  "Toxic Bellows"
lw_dl =  "Lamp of Dark Obstruction" 
lw_id =  "Parchment of Fire"
lw_dw =  "Lantern of Revelation"
lw_dt =  "Soul Savior"
# Region Keys
region_key = "Region Keys"
region_key_mk = "Mountain Kingdom Region Key"
region_key_cs = "Castle Stronghold Region Key"
region_key_sd = "Sky Dominion Region Key"
region_key_fr = "Forest Realm Region Key"
region_key_dl = "Desert Land Region Key"
region_key_id = "Ice Domain Region Key"
region_key_dw = "Dream World Region Key"
region_key_bf = "Battlefields Region Key"
# Wing keys
wing_key = "Wing Keys"
w_wing_key = "West Wing Key"
e_wing_key = "East Wing Key"
l_tower_key = "Lower Tower Key"
#filler
nothing = "Nothing"

victory = "Victory"
