hub = "Hub"
hub_short = "HB"
fp = "Forsaken Province"
fp_short = "FP"
mk = "Mountain Kingdom"
mk_short = "MK"
cs = "Castle Stronghold"
cs_short = "CS"
sd = "Sky Dominion"
sd_short = "SD"
fr = "Forest Realm"
fr_short = "FR"
dl = "Desert Land"
dl_short = "DL"
id = "Ice Domain"
id_short = "ID"
dw = "Dream World"
dw_short = "DW"
bf = "Battlefield"
bf_short = "BF"
dt = "Desecrated Temple"
dt_short = "DT"
uw = "Underworld"
uw_short = "UW"


